-- Mail-only fork. Email conversations, drafts, media, tags, views and sender IDs are preserved.
UPDATE inboxes SET enabled = false WHERE channel <> 'email';
UPDATE inboxes SET csat_enabled = false;
UPDATE conversations SET assigned_user_id = NULL, assigned_team_id = NULL, priority_id = NULL, sla_policy_id = NULL, next_sla_deadline_at = NULL;
UPDATE teams SET sla_policy_id = NULL, business_hours_id = NULL, conversation_assignment_type = 'Manual';
UPDATE users SET availability_status = 'offline' WHERE availability_status = 'away_and_reassigning';
UPDATE roles SET permissions = array_append(permissions, 'conversations:read_all') WHERE 'conversations:read' = ANY(permissions) AND NOT 'conversations:read_all' = ANY(permissions);
UPDATE views SET visibility = 'all', team_id = NULL WHERE visibility = 'team';
UPDATE roles SET permissions = array_append(permissions, 'conversations:write') WHERE 'conversations:read' = ANY(permissions) AND NOT 'conversations:write' = ANY(permissions);
UPDATE conversation_drafts SET meta = meta - 'macro_id' - 'macro_actions';
DO $$ BEGIN IF to_regclass('notification_email_queue') IS NOT NULL THEN DELETE FROM notification_email_queue WHERE notification_type::text IN ('assignment','automation') OR notification_type::text LIKE 'sla_%'; END IF; END $$;
DO $$ BEGIN IF to_regclass('user_notifications') IS NOT NULL THEN DELETE FROM user_notifications WHERE notification_type::text IN ('assignment','automation') OR notification_type::text LIKE 'sla_%'; END IF; END $$;
DROP TABLE IF EXISTS context_links CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS contact_notes CASCADE;
DROP TABLE IF EXISTS custom_attribute_definitions CASCADE;
DROP TABLE IF EXISTS ai_faq_suggestions CASCADE;
DROP TABLE IF EXISTS copilot_messages CASCADE;
DROP TABLE IF EXISTS ai_agent_events CASCADE;
DROP TABLE IF EXISTS ai_assistant_tools CASCADE;
DROP TABLE IF EXISTS ai_assistants CASCADE;
DROP TABLE IF EXISTS ai_tools CASCADE;
DROP TABLE IF EXISTS help_search_queries CASCADE;
DROP TABLE IF EXISTS help_article_feedback CASCADE;
DROP TABLE IF EXISTS help_articles CASCADE;
DROP TABLE IF EXISTS article_collections CASCADE;
DROP TABLE IF EXISTS help_centers CASCADE;
DROP TABLE IF EXISTS embeddings CASCADE;
DROP TABLE IF EXISTS ai_knowledge_base CASCADE;
DROP TABLE IF EXISTS ai_prompts CASCADE;
DROP TABLE IF EXISTS ai_providers CASCADE;
DROP TABLE IF EXISTS scheduled_sla_notifications CASCADE;
DROP TABLE IF EXISTS sla_events CASCADE;
DROP TABLE IF EXISTS applied_slas CASCADE;
DROP TABLE IF EXISTS csat_responses CASCADE;
DROP TABLE IF EXISTS macros CASCADE;
DROP TABLE IF EXISTS automation_rules CASCADE;
DROP TABLE IF EXISTS conversation_priorities CASCADE;
DROP TABLE IF EXISTS business_hours CASCADE;
DROP TABLE IF EXISTS sla_policies CASCADE;

DELETE FROM templates WHERE is_builtin AND name IN ('Conversation assigned','New reply from contact','SLA breach warning','SLA breached','CSAT request');
DELETE FROM settings WHERE key = 'app.business_hours_id' OR key LIKE 'ai_agent.%';
UPDATE users SET enabled = false WHERE type::text IN ('ai_assistant', 'visitor');
UPDATE templates SET body = replace(body, '/inboxes/assigned/', '/inboxes/all/');
UPDATE templates SET body = replace(body, 'a conversation assigned to you', 'a conversation you participated in') WHERE is_builtin;
